"""Standardized diagnostics shared by MHX workflows."""

from mhx.diagnostics.reduced_mhd import (
    DIAGNOSTICS_ENTRY_POINT_GROUP,
    DiagnosticContext,
    DiagnosticSpec,
    DiagnosticsRegistry,
    compute_reduced_mhd_diagnostics,
    default_diagnostics_registry,
    fit_exponential_growth,
    island_width_from_mode,
    kinetic_energy,
    load_diagnostics_entry_points,
    load_diagnostics_plugin_modules,
    magnetic_divergence_linf,
    magnetic_energy,
    mode_amplitude,
    reconnected_flux_amplitude,
    rutherford_island_full_width,
    select_fit_window,
    total_energy,
    trajectory_energies,
    trajectory_mode_amplitude,
)

__all__ = [
    "DiagnosticContext",
    "DIAGNOSTICS_ENTRY_POINT_GROUP",
    "DiagnosticSpec",
    "DiagnosticsRegistry",
    "compute_reduced_mhd_diagnostics",
    "default_diagnostics_registry",
    "fit_exponential_growth",
    "island_width_from_mode",
    "kinetic_energy",
    "load_diagnostics_entry_points",
    "load_diagnostics_plugin_modules",
    "magnetic_divergence_linf",
    "magnetic_energy",
    "mode_amplitude",
    "reconnected_flux_amplitude",
    "rutherford_island_full_width",
    "select_fit_window",
    "total_energy",
    "trajectory_energies",
    "trajectory_mode_amplitude",
]
