"""Plotting helpers."""

from mhx.plotting.diagnostics import write_diagnostic_figures_for_run
from mhx.plotting.reduced_mhd import (
    plot_arnoldi_ritz_values,
    plot_cosine_equilibrium_linearization_errors,
    plot_decay_amplitude,
    plot_decay_energy,
    plot_decay_relative_error,
    plot_diffusion_eigenvalue_error,
    plot_energy_history,
    plot_fkr_growth_rate_validation,
    plot_fkr_scaling,
    plot_fkr_validity_window,
    plot_flux_contours,
    plot_flux_gif,
    plot_harris_delta_prime,
    plot_ideal_tearing_scaling,
    plot_linear_tearing_dispersion_validation,
    plot_linear_tearing_eigenvalue_validation,
    plot_linear_tearing_layer_validation,
    plot_linear_tearing_timedomain_validation,
    plot_linearized_rhs_errors,
    plot_mode_amplitude,
    plot_nonlinear_current_sheet_bridge,
    plot_nonlinear_energy_budget,
    plot_periodic_current_sheet_spectrum,
    plot_periodic_current_sheet_timedomain,
    plot_plasmoid_scaling,
    plot_power_iteration_history,
    plot_reduced_mhd_eigenmode_errors,
    plot_timing_summary,
)

__all__ = [
    "plot_arnoldi_ritz_values",
    "plot_cosine_equilibrium_linearization_errors",
    "plot_decay_amplitude",
    "plot_decay_energy",
    "plot_decay_relative_error",
    "plot_diffusion_eigenvalue_error",
    "plot_energy_history",
    "plot_fkr_growth_rate_validation",
    "plot_fkr_scaling",
    "plot_fkr_validity_window",
    "plot_flux_contours",
    "plot_flux_gif",
    "plot_harris_delta_prime",
    "plot_ideal_tearing_scaling",
    "plot_linear_tearing_dispersion_validation",
    "plot_linear_tearing_eigenvalue_validation",
    "plot_linear_tearing_layer_validation",
    "plot_linear_tearing_timedomain_validation",
    "plot_linearized_rhs_errors",
    "plot_mode_amplitude",
    "plot_nonlinear_current_sheet_bridge",
    "plot_nonlinear_energy_budget",
    "plot_periodic_current_sheet_spectrum",
    "plot_periodic_current_sheet_timedomain",
    "plot_plasmoid_scaling",
    "plot_power_iteration_history",
    "plot_reduced_mhd_eigenmode_errors",
    "plot_timing_summary",
    "write_diagnostic_figures_for_run",
]
