"""Composable physics closures and source terms."""

from mhx.physics.equilibria import (
    CosineTearingEquilibrium,
    Equilibrium,
    EquilibriumMetadata,
    EquilibriumRegistry,
    PeriodicDoubleHarrisEquilibrium,
    ZeroEquilibrium,
    build_equilibrium,
    default_equilibrium_registry,
)
from mhx.physics.terms import (
    PHYSICS_API_VERSION,
    PHYSICS_ENTRY_POINT_GROUP,
    ElectronPressureTensorTerm,
    HyperResistivityTerm,
    PhysicsRegistry,
    PhysicsTerm,
    PhysicsTermMetadata,
    ToyHallOhmTerm,
    VorticityDragTerm,
    apply_physics_terms,
    build_physics_terms,
    default_physics_registry,
    load_physics_entry_points,
    load_physics_plugin_modules,
)

__all__ = [
    "CosineTearingEquilibrium",
    "Equilibrium",
    "EquilibriumMetadata",
    "EquilibriumRegistry",
    "ElectronPressureTensorTerm",
    "PHYSICS_API_VERSION",
    "PHYSICS_ENTRY_POINT_GROUP",
    "HyperResistivityTerm",
    "PhysicsRegistry",
    "PhysicsTerm",
    "PhysicsTermMetadata",
    "PeriodicDoubleHarrisEquilibrium",
    "ToyHallOhmTerm",
    "ZeroEquilibrium",
    "VorticityDragTerm",
    "build_equilibrium",
    "apply_physics_terms",
    "build_physics_terms",
    "default_equilibrium_registry",
    "default_physics_registry",
    "load_physics_entry_points",
    "load_physics_plugin_modules",
]
